variables:
  DOCKER_DRIVER: overlay2

image:
  name: docker/compose:latest

stages:
  - test

services:
  - docker:dind

before_script:
  - docker version
  - docker compose version

unit-test:
  stage: test
  script:
    - docker-compose down