workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
 - build
 - test

build:
  stage: build
  image: docker:git
  tags:
   - main
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/youngwishes/ywstore/$CI_DEFAULT_BRANCH:latest .
    - docker push $CI_REGISTRY/youngwishes/ywstore/$CI_DEFAULT_BRANCH:latest
  artifacts:
    paths:
      - build/*

test:
  stage: test
  image: docker:git
  dependencies:
    - build
  services:
    - postgres
  tags:
    - main

  script:
    - ls
    - docker compose up
#    - python3 -m pytest
