variables:
  DOCKER_DRIVER: overlay2

image:
  name: docker/compose:latest

stages:
  - test

services:
  - docker:dind

before_script:
  - curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
  - docker version
  - docker compose version

unit-test:
  stage: test
  script:
    - docker-compose down