variables:
  DOCKER_DRIVER: overlay2

# Official docker compose image.
image:
  name: docker/compose:latest

stages:
  - test

services:
  - docker:dind

before_script:
  - docker version
  - docker-compose version

unit-test:
  stage: test
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up tester-image