image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
- docker info
- apk add python python-dev py-pip build-base
- pip install docker-compose

unit-test:
  stage: test
  script:
    - docker-compose down -v
    - docker-compose up --build --detach --env_file=$ENV_FILE

