version: "3.8"

services:
  yshop-web:
    build: .
    image: "yshop-web"
    container_name: "yshop-web"
    command: uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8080:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      yshop-postgres:
        condition: service_healthy

  yshop-postgres:
    image: postgres
    container_name: "yshop-postgres"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 10s
      retries: 10
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
