version: "3.8"

services:
  ywstore-web:
    build: .
    image: "ywstore-web"
    container_name: "ywstore-web"
    command: ./entrypoint.sh
    ports:
      - "8080:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      ywstore-postgres:
        condition: service_healthy

  ywstore-postgres:
    image: postgres
    container_name: "ywstore-postgres"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 10s
      retries: 10
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ${DUMP_DIR}:/tmp/dumps
      - ${DUMP_DIR}/${DB_DUMP}:/docker-entrypoint-initdb.d/00dump.sql
