"""company initial

Revision ID: 6ac61ff5c45e
Revises: cfccaf3935c3
Create Date: 2023-11-14 20:43:48.763441

"""
from typing import Sequence, Union
from src.apps.company.enums import CompanyType
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "6ac61ff5c45e"
down_revision: Union[str, None] = "cfccaf3935c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("Название компании", sa.String(length=256), nullable=False),
        sa.Column("ФИО директора", sa.String(length=64), nullable=False),
        sa.Column(
            "Тип компании",
            sqlalchemy_utils.types.choice.ChoiceType(choices=CompanyType),
            nullable=False,
        ),
        sa.Column("Юридический адрес", sa.String(length=256), nullable=True),
        sa.Column("Фактический адрес", sa.String(length=256), nullable=True),
        sa.Column(
            "Дата регистрации",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("Дата обновления", sa.DateTime(timezone=True), nullable=True),
        sa.Column("Рейтинг", sa.Float(), nullable=True),
        sa.Column("Скрыта в системе", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_id"), "companies", ["id"], unique=False)
    op.create_index(
        op.f("ix_companies_Название компании"),
        "companies",
        ["Название компании"],
        unique=True,
    )
    op.create_index(
        op.f("ix_companies_Рейтинг"),
        "companies",
        ["Рейтинг"],
        unique=False,
    )
    op.create_table(
        "employees",
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("Ссылка на телеграм", sa.String(length=256), nullable=True),
        sa.Column("Ссылка на ВК", sa.String(length=256), nullable=True),
        sa.Column("Номер телефона", sa.String(length=32), nullable=True),
        sa.Column("Дополнительная информация о сотруднике", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("company_id", "user_id"),
    )
    op.create_index(
        op.f("ix_employees_company_id"),
        "employees",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employees_user_id"),
        "employees",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employees_user_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_company_id"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_companies_Рейтинг"), table_name="companies")
    op.drop_index(op.f("ix_companies_Название компании"), table_name="companies")
    op.drop_index(op.f("ix_companies_id"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
