"""Added association

Revision ID: cdd3e167b267
Revises: ff227fb94f88
Create Date: 2023-12-23 19:02:29.156921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cdd3e167b267"
down_revision: Union[str, None] = "ff227fb94f88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees",
        sa.Column("Дополнительная информация о сотруднике", sa.String(), nullable=True),
    )
    op.drop_column("employees", "Дополнительная информация о сотру")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees",
        sa.Column(
            "Дополнительная информация о сотру",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("employees", "Дополнительная информация о сотруднике")
    # ### end Alembic commands ###
